POST http://localhost:3001/api/recipes
Content-Type: application/json 
Authorization: bearer 

    {
      "src": "https://c5.staticflickr.com/9/8768/28941110956_b05ab588c1_b.jpg",
      "thumbnail": "https://c5.staticflickr.com/9/8768/28941110956_b05ab588c1_n.jpg",
      "thumbnailWidth": 258,
      "thumbnailHeight": 258,
      "caption": "Recipe2",
      "thumbnailCaption": "Recipe2"
  }
