DELETE http://localhost:3001/api/recipes/5f1ec187c4ef0004484b4be5
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVmMWVhYjcyMGZmZmYzNjFiODQ4ZjZlNyIsImlhdCI6MTU5NTg1NTU4N30.8adAk-LuLqpzS02UzKemSxw5F0Rgi-0LnKCWSPPPuVA